# Getting Started

## Tensors

In [1]:
import torch

# An uninitialized matrix is declared, but does not contain definite known values before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.
x = torch.empty(5, 3)
x

tensor([[1.6114e-19, 1.6020e-19, 4.4721e+21],
        [7.3840e+22, 1.3513e-14, 1.4917e-07],
        [4.4859e+21, 7.2150e+22, 2.4501e-09],
        [7.5553e+28, 5.2839e-11, 1.8888e+31],
        [4.7414e+16, 3.1434e-12, 8.0775e+17]])

In [2]:
# Construct a randomly initialized matrix:
x = torch.rand(5, 3)
x

tensor([[0.1768, 0.0252, 0.3825],
        [0.0727, 0.9963, 0.3651],
        [0.8616, 0.5529, 0.1209],
        [0.1791, 0.3994, 0.0585],
        [0.0548, 0.9263, 0.6761]])

In [3]:
# Construct a matrix filled zeros and of dtype long:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [4]:
# Construct a tensor from data
x = torch.tensor([5.5, 3])
print(x)
x.shape

tensor([5.5000, 3.0000])


torch.Size([2])

In [5]:
# or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.0870,  0.8627, -0.5135],
        [-0.7507,  0.4283,  0.5405],
        [ 0.6390,  0.2455, -0.1478],
        [-3.0340,  0.9263,  0.2301],
        [ 1.4263, -0.7427, -0.2583]])


In [6]:
x.size()
# torch.Size is in fact a tuple, so it supports all tuple operations.

torch.Size([5, 3])

## Operations

In [7]:
# Addition
y = torch.rand(5, 3)
print(x + y)
print(torch.add(x, y))

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

# Addition: in-place
# adds x to y
y.add_(x)
print(y)
# Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

tensor([[ 0.0859,  1.4640,  0.0112],
        [-0.0722,  1.0417,  1.2508],
        [ 1.3985,  0.8384, -0.0922],
        [-2.4628,  1.6542,  1.1757],
        [ 2.0619, -0.1439, -0.0910]])
tensor([[ 0.0859,  1.4640,  0.0112],
        [-0.0722,  1.0417,  1.2508],
        [ 1.3985,  0.8384, -0.0922],
        [-2.4628,  1.6542,  1.1757],
        [ 2.0619, -0.1439, -0.0910]])
tensor([[ 0.0859,  1.4640,  0.0112],
        [-0.0722,  1.0417,  1.2508],
        [ 1.3985,  0.8384, -0.0922],
        [-2.4628,  1.6542,  1.1757],
        [ 2.0619, -0.1439, -0.0910]])
tensor([[ 0.0859,  1.4640,  0.0112],
        [-0.0722,  1.0417,  1.2508],
        [ 1.3985,  0.8384, -0.0922],
        [-2.4628,  1.6542,  1.1757],
        [ 2.0619, -0.1439, -0.0910]])


In [8]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())


torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [9]:
# If you have a one element tensor, use .item() to get the value as a Python number

x = torch.randn(1)
print(x)
print(x.item())

tensor([0.0110])
0.010992790572345257


## Converting a Torch Tensor to a NumPy Array
Converting a Torch Tensor to a NumPy array and vice versa is a breeze.
The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

In [10]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [11]:
# See how the numpy array changed in value.
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Converting NumPy Array to Torch Tensor
See how changing the np array changed the Torch Tensor automatically



In [12]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)
# All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors
Tensors can be moved onto any device using the .to method.

In [13]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([1.0110], device='cuda:0')
tensor([1.0110], dtype=torch.float64)
